[book]
authors = ["zerone0x"]
language = "en"
multilingual = true
src = "src"
title = "Dot is learning"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css", "theme/css/fonts.css"]
additional-js  = ["theme/pagetoc.js"]
site_url = "/note/"

